Select ('VMID') as VMID, ('INSTANCEID') as ID, ('STATUS') as STATUS, ('STT') as STT 
UNION ALL
Select VMID, INSTANCEID, STATUS, FROM_UNIXTIME(SCHEDULEDTERMINATIONTIME/1000) as STT INTO OUTFILE '/root/scripts/expiredvms.csv' FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' FROM VMDATA_VIEW WHERE SCHEDULEDTERMINATIONTIME/1000 < UNIX_TIMESTAMP(NOW() - INTERVAL 1 DAY) AND SCHEDULEDTERMINATIONTIME <> -1;
